safe:        false
port:        8888

source:      .
destination: ./_site

future:      true
lsi:         false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink:   /:year/:month/:title

title:       TraMExp
author:      Rohan Goel
email:       rohangoel0296@gmail.com

exclude:     [_site]

# url: rohangoel96.github.io
baseurl: /tramexp

collections:
  travels:
    # name: Travels
    # url: /travels/
    output: true
    permalink: /:title/